# Обновляем агента на Linux хостах
# На хосте, на котором играем в папке files должны быть соответствующие файлы, RPM и j2

- name: Delete old agent and install zabbix-agent2
  hosts: agent-update
  
  tasks:
    - name: Stop zabbix agent daemon
      ansible.builtin.systemd:
        name: zabbix-agent.service
        state: stopped

    - name: Remove zabbix agent from system
      yum:
        name: zabbix-agent.x86_64
        state: absent

    - name: Copy .conf file to target hosts
      template:
        src: files/zabbix_agent2.j2
        dest: /tmp/

    - name: Copy RPM
      ansible.builtin.copy:
        src: files/zabbix-agent2-5.2.7-1.el7.x86_64.rpm
        dest: /tmp/

    - name: Install zabbix-agent2
      yum:
        name: /tmp/zabbix-agent2-5.2.7-1.el7.x86_64.rpm
        state: present

    - name: Delete new config file
      ansible.builtin.file:
        path: /etc/zabbix/zabbix_agent2.conf
        
    - name: Copy config file on target host to proper dir
         ansible.builtin.copy:
           src: /tmp/zabbix_agent2.j2
           dest: /etc/zabbix/zabbix_agent2.conf
           remote_src: yes
 
    - name: Start zabbix daemon
        ansible.builtin.systemd:
          name: zabbix-agent2.service
          state: started
 
     - name: Make sure a zabbix agent is running
        ansible.builtin.systemd:
          state: started
          name: zabbix-agent2.service
 
    - name: Enable zabbix agent daemon
        ansible.builtin.systemd:
          name: zabbix-agent2.service
          enabled: yes
          masked: no
