- name: Reinstall Zabbix Agent on Windows hosts

  hosts: citrix-defect
  
  tasks:

    - name: add the route to Zabbix Server
      ansible.windows.win_powershell:
        script: |
          route add 172.18.0.41 mask 255.255.255.255 10.154.7.1 metric 1

    - name: add firewall rule
      ansible.windows.win_powershell:
        script: |
          netsh advfirewall firewall add rule name="ZabbixAgent" protocol=TCP localport=10050 action=allow dir=IN  

    - name: change the owner of C:\Zabbix_agent
      ansible.windows.win_owner:
        path: C:\Zabbix_agent
        user: Administrator
        recurse: yes    

    - name: Remove C:\zabbix
      ansible.windows.win_file:
        path: C:\zabbix
        state: absent
        become: yes
        become_user: Administrator
    
    - name: Stoped Zabbix daemon on target hosts
      ansible.windows.win_service:
        name: "Zabbix Agent"
        state: stopped
 
    - name: Remove a service
      ansible.windows.win_service:
        name: "Zabbix Agent"
        state: absent   

    - name: Remove C:\Zabbix_agent
      ansible.windows.win_file:
        path: C:\Zabbix_agent
        state: absent
      
    - name: Create directory for agent
      ansible.windows.win_file:
        path: C:\zabbix
        state: directory

    - name: Copy executable file to target hosts
      ansible.windows.win_copy:
        src: files/zabbix_agentd.exe
        dest: C:\zabbix\zabbix_agentd.exe

    - name: Copy agent.conf to target hosts
      template:
        src: files/zabbix_agentd.j2
        dest: C:\zabbix_agentd.conf

    - name: Enable and start a new Zabbix Agent daemon
      ansible.windows.win_powershell:
        script: |
          C:\zabbix\zabbix_agentd.exe --install
      
    - name: Start Agent
      ansible.windows.win_service:
        name: "Zabbix Agent"
        state: started
